MFLO_HOME ?= ../../../
PRECISION  = DOUBLE
PROFILE    = FALSE
SUNDIALS_HOME?=/projects/co2rue/sundials

DEBUG      = TRUE
DEBUG      = FALSE

DIM       = 3

COMP	   = gnu

USE_MPI    = TRUE
USE_OMP    = FALSE 
USE_CUDA   = FALSE
USE_SUNDIALS = FALSE

Bpack   := ./Make.package 
Blocs   := . 

include ${MFLO_HOME}/Make.mflo
