#!/bin/bash
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=32
#SBATCH --time=01:00:00
#SBATCH --account=catmod
#SBATCH --partition=debug
#SBATCH --job-name=regtestcpu
#SBATCH --output=regout
#SBATCH --error=regerr

export MFLO_HOME=/home/hsitaram/codes/mesoflow/
export AMREX_HOME=/home/hsitaram/codes/amrex
. ./script_reg_testing.sh 32 srun ~/harienv.sh /scratch/hsitaram/mflo_results_cpu "DEBUG=TRUE"
