MFLO_HOME ?= ../../
PRECISION  = DOUBLE
PROFILE    = FALSE

DEBUG      = TRUE
DEBUG      = FALSE

DIM        = 3

COMP       = gnu

USE_MPI    = TRUE
USE_OMP    = FALSE
USE_CUDA   = FALSE

Bpack   := ./Make.package
Blocs   := .

USE_SUNDIALS = FALSE
SUNDIALS_HOME?=/projects/co2rue/sundials

include ${MFLO_HOME}/Make.mflo
